CREATE SEQUENCE PUBLIC.HIBERNATE_SEQUENCE START WITH 1;
CREATE TABLE PUBLIC.INGREDIENT
(
  ID   VARCHAR(255) NOT NULL,
  NAME VARCHAR(255),
  TYPE INTEGER
);
ALTER TABLE PUBLIC.INGREDIENT
  ADD CONSTRAINT PUBLIC.CONSTRAINT_1 PRIMARY KEY (ID);

CREATE TABLE PUBLIC.TACO
(
  ID         BIGINT       NOT NULL,
  CREATED_AT TIMESTAMP,
  NAME       VARCHAR(255) NOT NULL
);
ALTER TABLE PUBLIC.TACO
  ADD CONSTRAINT PUBLIC.CONSTRAINT_2 PRIMARY KEY (ID);
CREATE
MEMORY TABLE PUBLIC.TACO_INGREDIENTS(
    TACO_ID BIGINT NOT NULL,
    INGREDIENTS_ID VARCHAR(255) NOT NULL
);
CREATE TABLE PUBLIC.TACO_ORDER
(
  ID            BIGINT NOT NULL,
  CCCVV         VARCHAR(255),
  CC_EXPIRATION VARCHAR(255),
  CC_NUMBER     VARCHAR(255),
  CITY          VARCHAR(255),
  NAME          VARCHAR(255),
  PLACED_AT     TIMESTAMP,
  STATE         VARCHAR(2),
  STREET        VARCHAR(255),
  ZIP           VARCHAR(255)
);
ALTER TABLE PUBLIC.TACO_ORDER
  ADD CONSTRAINT PUBLIC.CONSTRAINT_F PRIMARY KEY (ID);
CREATE TABLE PUBLIC.TACO_ORDER_TACOS
(
  ORDER_ID BIGINT NOT NULL,
  TACOS_ID BIGINT NOT NULL
);
ALTER TABLE PUBLIC.TACO_ORDER_TACOS
  ADD CONSTRAINT PUBLIC.FKFWVQTNJFVIEW9E5F7BFQTD1NS FOREIGN KEY (TACOS_ID) REFERENCES PUBLIC.TACO (ID) NOCHECK;
ALTER TABLE PUBLIC.TACO_INGREDIENTS
  ADD CONSTRAINT PUBLIC.FK27RYCUH3MJAEPNBA0J6M8XL4Q FOREIGN KEY (TACO_ID) REFERENCES PUBLIC.TACO (ID) NOCHECK;
ALTER TABLE PUBLIC.TACO_INGREDIENTS
  ADD CONSTRAINT PUBLIC.FK7Y679Y77N5E75S3SS1V7FF14J FOREIGN KEY (INGREDIENTS_ID) REFERENCES PUBLIC.INGREDIENT (ID) NOCHECK;
ALTER TABLE PUBLIC.TACO_ORDER_TACOS
  ADD CONSTRAINT PUBLIC.FKCXWVDKNDAQMRXCEN10VKNEEXO FOREIGN KEY (ORDER_ID) REFERENCES PUBLIC.TACO_ORDER (ID) NOCHECK;